server:
  port: 6801
spring:
  application:
    name: feima-gateway
  zipkin:
    base-url: http://localhost:6101
#  redis:
#    host: localhost
#    password:
#    port: 6379
#    timeout: 5000ms
#    jedis:
#      pool:
#        max-active: 3
#        max-idle: 3
#        min-idle: 1
#        max-wait: 0ms
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:6603/eureka/